export const GET_CHECK_LOGIN = "GET_CHECK_LOGIN"
export const SET_CHECK_LOGIN = "SET_CHECK_LOGIN"
export const SET_LOADING = "SET_LOADING"
export const SET_LOGIN = "SET_LOGIN"
export const GET_LOGIN = "GET_LOGIN"
export const GET_NAVIGATE = "GET_NAVIGATE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const MOBILELIST_REQUEST = "MOBILELIST_REQUEST"
export const MOBILELIST_SUCCESS = "MOBILELIST_SUCCESS"
export const MOBILELIST_FAILURE = "MOBILELIST_FAILURE"

export const MOBILEDETAILS_REQUEST = "MOBILEDETAILS_REQUEST"
export const MOBILEDETAILS_SUCCESS = "MOBILEDETAILS_SUCCESS"
export const MOBILEDETAILS_FAILURE = "MOBILELIST_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = " ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = " REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE"