export const GET_CHECK_LOGIN = "GET_CHECK_LOGIN"
export const SET_CHECK_LOGIN = "SET_CHECK_LOGIN"
export const SET_LOADING = "SET_LOADING"
export const SET_LOGIN = "SET_LOGIN"
export const GET_LOGIN = "GET_LOGIN"
export const GET_NAVIGATE = "GET_NAVIGATE"

//LOGIN_REQUEST
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
//LOGIN_REQUEST
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//  MOBILELIST_REQUEST 
export const MOBILELIST_REQUEST = "MOBILELIST_REQUEST"
export const MOBILELIST_SUCCESS = "MOBILELIST_SUCCESS"
export const MOBILELIST_FAILURE = "MOBILELIST_FAILURE"


//  MOBILEDETAILS
export const MOBILEDETAILS_REQUEST = "MOBILEDETAILS_REQUEST"
export const MOBILEDETAILS_SUCCESS = "MOBILEDETAILS_SUCCESS"
export const MOBILEDETAILS_FAILURE = "MOBILELIST_FAILURE"


//  ADD_TO_CART MOBILE
export const ADD_TO_CART_REQUEST_MOBILE = "ADD_TO_CART_REQUEST_MOBILE"
//ADD TO CART GROCERY
export const ADD_TO_CART_REQUEST_GROCERY = "ADD_TO_CART_REQUEST_GROCERY"

export const ADD_TO_CART_SUCCESS= " ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"



// REMOVE_FROM_CART
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = " REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE"

// ADD_SAME_PRODUCT_IN
export const ADD_SAME_PRODUCT_IN_CART_REQUEST = "ADD_SAME_PRODUCT_IN_CART_REQUEST"
export const ADD_SAME_PRODUCT_IN_CART_SUCCESS = " ADD_SAME_PRODUCT_IN_CART_SUCCESS"
export const ADD_SAME_PRODUCT_IN_CART_FAILURE = "ADD_SAME_PRODUCT_IN_CART_FAILURE"

// place order
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = " PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE"

//GROCERY
export const GROCERY_REQUEST = "GROCERY_REQUEST"
export const GROCERY_SUCCESS = " GROCERY_SUCCESS"
export const GROCERY_FAILURE = "GROCERY_FAILURE"